### ISSUE TITLE
Variable declaration and initialization can be done within for loop declaration

### ISSUE THREAD

**Issue by nishant-jain-94** [sro-boeing-wave-2/remove-duplicate-items-js-problem-vermarahul18#1]
https://github.com/sro-boeing-wave-2/remove-duplicate-items-js-problem-vermarahul18/blob/934894c91ffbea4b000e4745b11b3add0fdc61bc/index.js#L7-L13

**Comment by nishant-jain-94** [comment]
Also Set constructor accepts an array. So ideally `Array.from(new Set(items))` can be done

**Comment by vermarahul18** [comment]
Used the es6 convention and directly accepting array in set constructor.
